<option value="disabled" disabled selected>Select your server</option>
<option value="euw">Europe West</option>
<option value="na">North America</option>
<option value="br">Brazil</option>
<option value="eune">Europe Nordic & East</option>
<option value="jp">Japan</option>
<option value="kr">Korea</option>
<option value="lan">Latin America North</option>
<option value="las">Latin America South</option>
<option value="oce">Oceania</option>
<option value="tr">Turkey</option>
<option value="ru">Russia</option>
<option value="pbe">Public Beta Environment</option>